//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STINFOS", Namespace="http://moriahconsultoria.ddns.net:83/")]
    [System.SerializableAttribute()]
    public partial class STINFOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WebApplication1.ServiceReference1.ARRAYOFSTRING AINFOUSUARIOLOGADOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public WebApplication1.ServiceReference1.ARRAYOFSTRING AINFOUSUARIOLOGADO {
            get {
                return this.AINFOUSUARIOLOGADOField;
            }
            set {
                if ((object.ReferenceEquals(this.AINFOUSUARIOLOGADOField, value) != true)) {
                    this.AINFOUSUARIOLOGADOField = value;
                    this.RaisePropertyChanged("AINFOUSUARIOLOGADO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ARRAYOFSTRING", Namespace="http://moriahconsultoria.ddns.net:83/", ItemName="STRING")]
    [System.SerializableAttribute()]
    public class ARRAYOFSTRING : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STINFOSEDITADO", Namespace="http://moriahconsultoria.ddns.net:83/")]
    [System.SerializableAttribute()]
    public partial class STINFOSEDITADO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CELULARField;
        
        private string CODCLIField;
        
        private string EMAILField;
        
        private string EMPRESAField;
        
        private string FONEField;
        
        private string TITULOIMAGEMField;
        
        private string USUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CELULAR {
            get {
                return this.CELULARField;
            }
            set {
                if ((object.ReferenceEquals(this.CELULARField, value) != true)) {
                    this.CELULARField = value;
                    this.RaisePropertyChanged("CELULAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CODCLI {
            get {
                return this.CODCLIField;
            }
            set {
                if ((object.ReferenceEquals(this.CODCLIField, value) != true)) {
                    this.CODCLIField = value;
                    this.RaisePropertyChanged("CODCLI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string EMPRESA {
            get {
                return this.EMPRESAField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPRESAField, value) != true)) {
                    this.EMPRESAField = value;
                    this.RaisePropertyChanged("EMPRESA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FONE {
            get {
                return this.FONEField;
            }
            set {
                if ((object.ReferenceEquals(this.FONEField, value) != true)) {
                    this.FONEField = value;
                    this.RaisePropertyChanged("FONE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string TITULOIMAGEM {
            get {
                return this.TITULOIMAGEMField;
            }
            set {
                if ((object.ReferenceEquals(this.TITULOIMAGEMField, value) != true)) {
                    this.TITULOIMAGEMField = value;
                    this.RaisePropertyChanged("TITULOIMAGEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://moriahconsultoria.ddns.net:83/", ConfigurationName="ServiceReference1.WSPOR02SOAP")]
    public interface WSPOR02SOAP {
        
        // CODEGEN: Generating message contract since the wrapper name (AUTLSTRESPONSE) of message AUTLSTResponse does not match the default value (AUTLST)
        [System.ServiceModel.OperationContractAttribute(Action="http://moriahconsultoria.ddns.net:83/AUTLST", ReplyAction="*")]
        WebApplication1.ServiceReference1.AUTLSTResponse AUTLST(WebApplication1.ServiceReference1.AUTLSTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moriahconsultoria.ddns.net:83/AUTLST", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.AUTLSTResponse> AUTLSTAsync(WebApplication1.ServiceReference1.AUTLSTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SETPERFILRESPONSE) of message SETPERFILResponse does not match the default value (SETPERFIL)
        [System.ServiceModel.OperationContractAttribute(Action="http://moriahconsultoria.ddns.net:83/SETPERFIL", ReplyAction="*")]
        WebApplication1.ServiceReference1.SETPERFILResponse SETPERFIL(WebApplication1.ServiceReference1.SETPERFILRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://moriahconsultoria.ddns.net:83/SETPERFIL", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.SETPERFILResponse> SETPERFILAsync(WebApplication1.ServiceReference1.SETPERFILRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AUTLST", WrapperNamespace="http://moriahconsultoria.ddns.net:83/", IsWrapped=true)]
    public partial class AUTLSTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://moriahconsultoria.ddns.net:83/", Order=0)]
        public string _CNOMECLIENTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://moriahconsultoria.ddns.net:83/", Order=1)]
        public string _CSENHACLIENTE;
        
        public AUTLSTRequest() {
        }
        
        public AUTLSTRequest(string _CNOMECLIENTE, string _CSENHACLIENTE) {
            this._CNOMECLIENTE = _CNOMECLIENTE;
            this._CSENHACLIENTE = _CSENHACLIENTE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AUTLSTRESPONSE", WrapperNamespace="http://moriahconsultoria.ddns.net:83/", IsWrapped=true)]
    public partial class AUTLSTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://moriahconsultoria.ddns.net:83/", Order=0)]
        public WebApplication1.ServiceReference1.STINFOS AUTLSTRESULT;
        
        public AUTLSTResponse() {
        }
        
        public AUTLSTResponse(WebApplication1.ServiceReference1.STINFOS AUTLSTRESULT) {
            this.AUTLSTRESULT = AUTLSTRESULT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SETPERFIL", WrapperNamespace="http://moriahconsultoria.ddns.net:83/", IsWrapped=true)]
    public partial class SETPERFILRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://moriahconsultoria.ddns.net:83/", Order=0)]
        public WebApplication1.ServiceReference1.STINFOSEDITADO STINFOSEDITADO;
        
        public SETPERFILRequest() {
        }
        
        public SETPERFILRequest(WebApplication1.ServiceReference1.STINFOSEDITADO STINFOSEDITADO) {
            this.STINFOSEDITADO = STINFOSEDITADO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SETPERFILRESPONSE", WrapperNamespace="http://moriahconsultoria.ddns.net:83/", IsWrapped=true)]
    public partial class SETPERFILResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://moriahconsultoria.ddns.net:83/", Order=0)]
        public string SETPERFILRESULT;
        
        public SETPERFILResponse() {
        }
        
        public SETPERFILResponse(string SETPERFILRESULT) {
            this.SETPERFILRESULT = SETPERFILRESULT;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSPOR02SOAPChannel : WebApplication1.ServiceReference1.WSPOR02SOAP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPOR02SOAPClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.WSPOR02SOAP>, WebApplication1.ServiceReference1.WSPOR02SOAP {
        
        public WSPOR02SOAPClient() {
        }
        
        public WSPOR02SOAPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPOR02SOAPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPOR02SOAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPOR02SOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.AUTLSTResponse WebApplication1.ServiceReference1.WSPOR02SOAP.AUTLST(WebApplication1.ServiceReference1.AUTLSTRequest request) {
            return base.Channel.AUTLST(request);
        }
        
        public WebApplication1.ServiceReference1.STINFOS AUTLST(string _CNOMECLIENTE, string _CSENHACLIENTE) {
            WebApplication1.ServiceReference1.AUTLSTRequest inValue = new WebApplication1.ServiceReference1.AUTLSTRequest();
            inValue._CNOMECLIENTE = _CNOMECLIENTE;
            inValue._CSENHACLIENTE = _CSENHACLIENTE;
            WebApplication1.ServiceReference1.AUTLSTResponse retVal = ((WebApplication1.ServiceReference1.WSPOR02SOAP)(this)).AUTLST(inValue);
            return retVal.AUTLSTRESULT;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.AUTLSTResponse> WebApplication1.ServiceReference1.WSPOR02SOAP.AUTLSTAsync(WebApplication1.ServiceReference1.AUTLSTRequest request) {
            return base.Channel.AUTLSTAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.AUTLSTResponse> AUTLSTAsync(string _CNOMECLIENTE, string _CSENHACLIENTE) {
            WebApplication1.ServiceReference1.AUTLSTRequest inValue = new WebApplication1.ServiceReference1.AUTLSTRequest();
            inValue._CNOMECLIENTE = _CNOMECLIENTE;
            inValue._CSENHACLIENTE = _CSENHACLIENTE;
            return ((WebApplication1.ServiceReference1.WSPOR02SOAP)(this)).AUTLSTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.SETPERFILResponse WebApplication1.ServiceReference1.WSPOR02SOAP.SETPERFIL(WebApplication1.ServiceReference1.SETPERFILRequest request) {
            return base.Channel.SETPERFIL(request);
        }
        
        public string SETPERFIL(WebApplication1.ServiceReference1.STINFOSEDITADO STINFOSEDITADO) {
            WebApplication1.ServiceReference1.SETPERFILRequest inValue = new WebApplication1.ServiceReference1.SETPERFILRequest();
            inValue.STINFOSEDITADO = STINFOSEDITADO;
            WebApplication1.ServiceReference1.SETPERFILResponse retVal = ((WebApplication1.ServiceReference1.WSPOR02SOAP)(this)).SETPERFIL(inValue);
            return retVal.SETPERFILRESULT;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.SETPERFILResponse> WebApplication1.ServiceReference1.WSPOR02SOAP.SETPERFILAsync(WebApplication1.ServiceReference1.SETPERFILRequest request) {
            return base.Channel.SETPERFILAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.SETPERFILResponse> SETPERFILAsync(WebApplication1.ServiceReference1.STINFOSEDITADO STINFOSEDITADO) {
            WebApplication1.ServiceReference1.SETPERFILRequest inValue = new WebApplication1.ServiceReference1.SETPERFILRequest();
            inValue.STINFOSEDITADO = STINFOSEDITADO;
            return ((WebApplication1.ServiceReference1.WSPOR02SOAP)(this)).SETPERFILAsync(inValue);
        }
    }
}
